### ISSUE TITLE
Roadmap for extending the plugin

### ISSUE THREAD

**Issue by ryanwelcher** [10up/classifai-for-wordpress#28]
This plugin, in it's most distilled form, simply provides AI services from service providers. If we can approach the plugin from that point of view, we can structure things to allow us to add new services or service providers fairly simply.

At this point, the plugin supports Natural Language Processing ( service ) from IBM Watson ( service provider ).

### New Services
I think one that has potential is Image Recognition. This could be applied to Featured Images or media uploads. It would make sense for us to use the Watson tool for our first offering.

### New Service Providers
I have some experience working with AWS using both the NLP ( Comprehend ) and Image Recognition ( Rekognition ) tools so that may be a good place to start if/when we decide to add another provider.

**Comment by jeffpaul** [comment]
Note that I'm closing this in favor of individual issues for items identified: #2, #48, #49, #50, #51, #52.

As more ideas arise, we'll open individual issues for each.
